Edit filename to resolve error when clone repo on windows. Add data source model to gooddata library
gooddata/gooddata-ruby pull request #1711
Opened 2020-12-04 04:00 UTC by tuannnh

@Seikitsu Could you approve this PR?

2020-12-04 04:11 UTC, danh-ung commented
PR, commit message MUST link to a JIRA ticket.

2020-12-04 11:14 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/514/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/517/ : FAILURE in 7h 13m 47s

2020-12-08 03:01 UTC, tuannnh commented
@danh-ung Hi, this PR linked to this JIRA ticket: [https://jira.intgdc.com/browse/BCO-1119](url)

2020-12-08 03:41 UTC, danh-ung commented
@tuannnh PR and commit message have to follow commit policy, see https://confluence.intgdc.com/display/pap/Commit+Policy+Examples. In short, your PR and commit message should be "FEATURE: BCO-1119 Introduce data sources API to GDC Ruby SDK"

2020-12-08 03:52 UTC, tuannnh commented
Hi @danh-ung, thank you for supporting. I have changed the commit message and PR. Is it anything else I have to follow?

2020-12-08 04:12 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/515/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/518/ : SUCCESS in 21m 06s

2020-12-09 09:59 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/516/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/519/ : SUCCESS in 20m 51s

2020-12-10 04:00 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/517/ : SUCCESS in 5s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/520/ : SUCCESS in 21m 06s

2020-12-14 14:59 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/518/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/521/ : SUCCESS in 20m 21s

2020-12-15 10:11 UTC, hung-nguyen-hoang commented on lib/gooddata/models/data_source.rb
> +# Copyright (c) 2010-2017 GoodData Corporation. All rights reserved.
Please update the copyright to "# Copyright (c) 2010-2020 GoodData Corporation. All rights reserved."

2020-12-15 10:46 UTC, hung-nguyen-hoang commented on lib/gooddata/models/data_source.rb
> +        data_source_id = data_source[:id]
Please verify the id existing in data source json data

2020-12-15 10:52 UTC, hung-nguyen-hoang commented
Currently the code already existing the data source APIs in https://github.com/gooddata/gooddata-ruby/blob/master/lib/gooddata/helpers/data_source_helpers.rb So please help refactor move the data source APIs existing in data_source_helpers.rb to the new data sources API.
Thank you.

2020-12-16 04:50 UTC, tuannnh commented
> Currently the code already existing the data source APIs in https://github.com/gooddata/gooddata-ruby/blob/master/lib/gooddata/helpers/data_source_helpers.rb So please help refactor move the data source APIs existing in data_source_helpers.rb to the new data sources API.
> Thank you.

After moving the APIs from data_source_helpers.rb file. Can I remove that file?

2020-12-16 07:19 UTC, hung-nguyen-hoang commented
Yes, please remove it. Thank you.

2020-12-16 07:37 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/519/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/522/ : FAILURE in 6m 18s

2020-12-16 08:19 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/520/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/523/ : SUCCESS in 26m 22s

2020-12-21 08:52 UTC, danh-ung requested changes

2020-12-21 08:52 UTC, danh-ung commented on lib/gooddata/models/data_source.rb
> +    class << self
models/data_source.rb should represent for dataSource object with functions to CRUD:
- constructor: create new datasource object or load it from server.
- create: create new datasource.
- save: create or update datasource
- all: list data sources

You can inspire from other resources process.rb or schedule.rb

2020-12-21 08:57 UTC, danh-ung commented
Please add automation tests, see similar spec/integration/models/schedule_spec.rb

2021-01-19 02:59 UTC, danh-ung commented
Closed, replaced by https://github.com/gooddata/gooddata-ruby/pull/1714

2021-01-19 03:00 UTC, closed without merging